### PR TITLE
Routes with both render and redirect are now rejected

### PR DESCRIPTION
**Pull request by tom-pang**
I'm not too sure about the design on this one.

### CODE REVIEW

**Comment by tom-pang** [comment]
Commit 484dc20 breaks the tests (I was dumb). Apologies for that.

**Comment by garybernhardt** [comment]
I'm not feeling this RawRoutes thing. What about doing the validation when the RouteOptions are built, since you have access to the original routes hash there? It's a different kind of validation than what ValidatesRoutes is doing right now, but it will be a lot cleaner. I think I'm OK with having two validation steps: one that validates a route (operates on the RouteOptions) and one that validates a route set (operates on a Router).

**Comment by garybernhardt** [comment]
Oh, I see: that's what you were doing before the refactor. I like that version more, though I think that the validation should be triggered in the route construction rather than in the router itself. That makes it impossible to build a bad route even if there's no router present.

**Comment by tom-pang** [comment]
Yeah, looking over it now I prefer the version before the refactor. The validation can probably be pushed into "ValidatesRouteOptions" vs "ValidatesRouteSet" as well. I'll do that tomorrow then.

(/me wishes he was doing this on a branch)

**Pull request closed without merging**
