### PR TITLE
steal rails redirect_to rspec matcher

### PR DESCRIPTION
**Pull request by tom-pang**
Unsure how I feel about this one

### CODE REVIEW

**Comment by garybernhardt** [comment]
What's the equality situation with Rack responses? Could we have a helper method that constructs a redirect response for you, then compare against that?

If we wrapped Rack responses with our own objects, it would be easy. We could have a RedirectResponse class.

**Comment by tom-pang** [comment]
So then the spec would be

`response.should == redirect_to('/my_resource')`? I prefer using a matcher, personally.

**Comment by garybernhardt** [comment]
Alright, I'm OK with the matcher.

Is there somewhere to put it other than on Kernel, though? I assume there's some standard RSpec practice for this; I don't ever write my own matchers.

**Comment by tom-pang** [comment]
I don't often write my own matchers, but the duplication was bugging me when I was writing the redirect to full urls thing.

**Pull request merged**
