### PR TITLE
Route PUT/DELETE over POST

### PR DESCRIPTION
**Pull request by tom-pang**
Uses Rack::MethodOverride (untested though).

The Router is now a full Rack app, the App just wraps it in
middleware.

### CODE REVIEW

**Comment by garybernhardt** [comment]
But does it do anything? ;)

**Comment by tom-pang** [comment]
I checked it manually, it does. If you pass _method as a param, it calls raptor with that method. Want me to add a couple of integration tests?

**Comment by garybernhardt** [comment]
Yeah, I think there should be one. I'm not sure where it belongs, though. I guess app_spec? The only example in there is a giant integration test anyway.

**Comment by garybernhardt** [comment]
Rebased.

**Pull request closed without merging**
