### PR TITLE
Custom responders

### PR DESCRIPTION
**Pull request by obrok**
~ Pushed the responsibility for matching a responder to params to the responders themselves
- Added the ability to specify a custom responder class

### CODE REVIEW

**Comment by garybernhardt** [comment]
I like this change. The only thing that worries me is the much wider interface on responders. It was easy to look at `PlaintextResponder.new(text)` and know what was happening. Now it's `PlaintextResponder.new(app_module, parent_path, {:text => text})`, which is less direct.

Of course, I recognize that the responder interface has to be uniform if we're going to support custom responders. Paweł, can you explain your use case for custom responders?

Also, @tcrayford, have you looked at this yet?

**Comment by obrok** [comment]
The particular thing we needed was a responder which set content type (for json in this case) and status codes. We figured it would be better to add the ability to insert custom responders instead of just sticking another one in there.

**Comment by tom-pang** [comment]
I think we need to rethink the responder design somewhat:

What happens when our users app wants to respond with json & a status codes, or any other combinations of responders?
Whilst this pull request lets them add a custom responder, having to write one for each combination of responses seems weird to me.

Furthermore: what happens if a user wants to conditionally return different types of responders? (I'm thinking about http caching here). We could let the user handle that via raising an exception (if the response is still valid via etag/last modified), then catching that error in another route, but that sucks somewhat (to me anyway).

**Comment by obrok** [comment]
One thing that I thought would help here is if responders were chosen 
per request instead of per path. That way for example one path may serve 
different formats of responses like respond_with in Rails does.

**Comment by garybernhardt** [comment]
I agree with both comments. We need to support common cases without requiring users to write a responder. We also need to allow specifying different responses to the same route.

In the module inversion thread, we talked about formalizing the idea of "response models" (currently named subjects). We could allow them to specify the response, but how? A specific method name on the response model?

In any case, I think that users should be dealing with Rack responses if they need to do custom HTTP stuff. Raptor responders are really just big Rack::Response factories.

**Comment by tom-pang** [comment]
I agree with using rack responses for really custom http stuff.

One of the conflicts I've been having here is, apart from the arguments to the interactor (and with custom injectors, not always then), most of the user's app is completely non-http dependent (which is super nice). If we add a way to customize responders in the subject/response model, we're going to have that thing know about http, which it doesn't right now.

**Comment by garybernhardt** [comment]
I was thinking that the subject would reference the response class to use. That keeps it from directly knowing about HTTP directly, but allows it to specify the behavior it wants at a high level.

**Comment by tom-pang** [comment]
I'm confused by that last comment. Can you give an example?

**Comment by obrok** [comment]
Isn't translating generic responses into HTTP-speak exactly the task of responders? I think it's OK for the responders (even user-provided ones) to be HTTP-aware as long as the user is isolated in the _rest_ of his app from that.

**Comment by garybernhardt** [comment]
@tcrayford E.g., your subject is an object with a `response` method (or `responder`) method that returns a class. It feels weird, but it does remove HTTP knowledge from the subject.

**Comment by garybernhardt** [comment]
@obrok, You're right; we need some way to translate high-level ideas directly into HTTP. I think the main question now is where the responder is specified.

If it's specified in the route, it can't change dynamically based on what happens in the delegate/interactor. For example, you wouldn't be able to return an HTTP 400, 403, etc. conditionally.

If the responder is specified by the subject—the object returned by the delegate/interactor—then it can vary depending on what happens as the request is processed.

**Comment by obrok** [comment]
My understanding was that the subject/response model would contain abstract concepts such as #success? or #errors and the responder's role is to change this into for example a JSON error hash with 4xx status or into a login page with error flash or whatever. If that is correct then the responder does have the information to select a 2xx or 4xx status. Am I missing something?

**Comment by tom-pang** [comment]
orbrok: yeah. Users need to be able to specify custom responders per request/response. Otherwise they can't e.g. send 304 responses when the page to be rendered is already browser cached.

If we do what Gary's suggesting, the user can just monkey patch `responder` into the subject class in the files that know about http stuff.

**Comment by garybernhardt** [comment]
If I understand correctly, @obrok is imagining responders mapping one-to-one with delegates, and @tcrayford is imagining them mapping one-to-one with HTTP response ("forbidden", "not found", etc.)

In the first version (big responders), the responders have knowledge about whether, for example, a request failed and why. They translate the failures into different HTTP status codes, serialize content differently, etc.

In the small-responder version, there's e.g. a ForbiddenResponder that returns HTTP 403, and the delegate somehow indicates that it should be used.

Big-responder insulates the delegate from more decisions about how to respond, but it also requires creating many more responders. I think that we need an example...

**Comment by garybernhardt** [comment]
I think that big responders are closer to what Raptor's responders are now, but we didn't plan to expose that. We wanted to expose something closer to the small-responder, where there's a fixed set of HTTP things that you can do (since HTTP is a mostly-fixed protocol).

The problem is that the mapping of delegate to responder varies tremendously. Sometimes, a delegate might need multiple responders for a single request (e.g., JSON rendering and caching might be separate). Sometimes, many delegates need to use the same responder (e.g., caching again: you probably want caching most of the time).

If responders are specified in the routes, they can't be conditional and you can't compose them easily. If they're specified in the subject, you may end up repeating yourself in each subject class.

**Comment by tom-pang** [comment]
Can we let the interactor return a response? Jersey does this (when the subject can't be turned into a response by the framework).

That might be a bad idea, it might not. Just food for thought.

**Comment by garybernhardt** [comment]
But it would still need to return a subject to be presented...

**Comment by tom-pang** [comment]
Closing this, as the design has changed, and we're going to do something else (tm).

**Pull request closed without merging**
